export const expenseCategories = [
  { label: "Housing", value: "housing" },
  { label: "Food", value: "food" },
  { label: "Transportation", value: "transportation" },
  { label: "Utilities", value: "utilities" },
  { label: "Insurance", value: "insurance" },
  { label: "Healthcare", value: "healthcare" },
  { label: "Debt Payments", value: "debt" },
  { label: "Savings & Investments", value: "savings" },
  { label: "Personal Care", value: "personal_care" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Education", value: "education" },
  { label: "Gifts & Donations", value: "gifts_donations" },
  { label: "Childcare", value: "childcare" },
  { label: "Pet Care", value: "pet_care" },
  { label: "Clothing", value: "clothing" },
  { label: "Subscriptions", value: "subscriptions" },
  { label: "Miscellaneous", value: "misc" },
];